# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fulltext_Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fulltext_search(object):
    def setupUi(self, fulltext_search):
        fulltext_search.setObjectName("fulltext_search")
        fulltext_search.resize(990, 639)
        self.Open = QtWidgets.QPushButton(fulltext_search)
        self.Open.setGeometry(QtCore.QRect(10, 50, 241, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        self.Open.setFont(font)
        self.Open.setDefault(False)
        self.Open.setObjectName("Open")
        self.titleList = QtWidgets.QListWidget(fulltext_search)
        self.titleList.setGeometry(QtCore.QRect(260, 50, 711, 111))
        self.titleList.setObjectName("titleList")
        self.showFile = QtWidgets.QTextBrowser(fulltext_search)
        self.showFile.setGeometry(QtCore.QRect(20, 190, 951, 351))
        self.showFile.setObjectName("showFile")
        self.searchButton = QtWidgets.QPushButton(fulltext_search)
        self.searchButton.setGeometry(QtCore.QRect(170, 130, 81, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.label_2 = QtWidgets.QLabel(fulltext_search)
        self.label_2.setGeometry(QtCore.QRect(590, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(27)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(fulltext_search)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 121, 16))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.searchText = QtWidgets.QTextEdit(fulltext_search)
        self.searchText.setGeometry(QtCore.QRect(20, 130, 141, 31))
        self.searchText.setObjectName("searchText")
        self.widget = QtWidgets.QWidget(fulltext_search)
        self.widget.setGeometry(QtCore.QRect(20, 560, 253, 66))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.characters = QtWidgets.QLabel(self.widget)
        self.characters.setMinimumSize(QtCore.QSize(251, 0))
        self.characters.setObjectName("characters")
        self.verticalLayout.addWidget(self.characters)
        self.words = QtWidgets.QLabel(self.widget)
        self.words.setMinimumSize(QtCore.QSize(221, 0))
        self.words.setObjectName("words")
        self.verticalLayout.addWidget(self.words)
        self.sentences = QtWidgets.QLabel(self.widget)
        self.sentences.setMinimumSize(QtCore.QSize(141, 0))
        self.sentences.setObjectName("sentences")
        self.verticalLayout.addWidget(self.sentences)

        self.retranslateUi(fulltext_search)
        QtCore.QMetaObject.connectSlotsByName(fulltext_search)

    def retranslateUi(self, fulltext_search):
        _translate = QtCore.QCoreApplication.translate
        fulltext_search.setWindowTitle(_translate("fulltext_search", "Form"))
        self.Open.setText(_translate("fulltext_search", "Load File"))
        self.searchButton.setText(_translate("fulltext_search", "search"))
        self.label_2.setText(_translate("fulltext_search", "TITLE"))
        self.label_3.setText(_translate("fulltext_search", "Text Search："))
        self.characters.setText(_translate("fulltext_search", "Number of characters: "))
        self.words.setText(_translate("fulltext_search", "Number of words: "))
        self.sentences.setText(_translate("fulltext_search", "Number of sentences:"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     fulltext_search = QtWidgets.QWidget()
#     ui = Ui_fulltext_search()
#     ui.setupUi(fulltext_search)
#     fulltext_search.show()
#     sys.exit(app.exec_())
